name: s
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: gotham
      fonts:
        - asset: fonts/Gotham-Bold.otf
        - asset: fonts/Gotham-Light.otf
        - asset: fonts/Gotham-Medium.otf
        - asset: fonts/Gotham-Thin.otf
        - asset: fonts/Gotham-Ultra.otf
        - asset: fonts/Gotham-XLight.otf
        - asset: fonts/Gotham-Book.otf
        - asset: fonts/Gotham-Black.otf
